name: push and pr release

on:
  push:
    branches:
      - develop
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - develop
    paths-ignore:
      - '**.md'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build Develop
        if: ${{ github.ref_name == 'develop' }}
        uses: gradle/gradle-build-action@v2
        with:
          build-root-directory: ${{ inputs.source }}
          cache-read-only: ${{ github.ref != 'refs/heads/develop' }} # only update the cache on the default branch https://github.com/gradle/gradle-build-action#optimizing-cache-effectiveness
          arguments: |
            -Psemver.develop.stage=beta 
            clean build
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Build Develop
        if: ${{ github.ref_name != 'develop' && github.ref_name != 'main' }}
        uses: gradle/gradle-build-action@v2
        with:
          build-root-directory: ${{ inputs.source }}
          cache-read-only: ${{ github.ref != 'refs/heads/develop' }} # only update the cache on the default branch https://github.com/gradle/gradle-build-action#optimizing-cache-effectiveness
          arguments: |
            -Psemver.develop.stage=alpha 
            clean build
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: build/test-results/**/*.xml

      - name: Publish Test Report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: build/reports/tests/test/*

      - name: Stop Gradle daemons
        run: ./gradlew --stop