name: push and pr release

on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - develop
    paths-ignore:
      - '**.md'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Show Git Repo debug
        run: | 
          git status
          git --no-pager log
          git --no-pager log refs/heads/main
          git show-branch --current -g

      - name: Restore Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-          

      - name: Build and Release Main
        if: ${{ github.ref_name == 'main' }}
        run: |
          ./gradlew --no-daemon clean build -Psemver.main.scope=patch -PgitHubTokenProp=${{ github.token }} publishToSonatype closeAndReleaseSonatypeStagingRepository githubRelease
        env:
          TOKEN_GITHUB_ACTION: '${{ secrets.GITHUB_TOKEN }}'
          OSS_USER: '${{ secrets.OSS_USER }}'
          OSS_TOKEN: '${{ secrets.OSS_TOKEN }}'
          OSS_STAGING_PROFILE_ID: '${{ secrets.OSS_STAGING_PROFILE_ID }}'
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEYID }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGPASSWORD }}

      - name: Build and Release Develop
        if: ${{ github.ref_name == 'develop' }}
        run: |
          ./gradlew --no-daemon clean build -Psemver.develop.stage=beta -PgitHubTokenProp=${{ github.token }} 
        env:
          TOKEN_GITHUB_ACTION: '${{ secrets.GITHUB_TOKEN }}'
          OSS_USER: '${{ secrets.OSS_USER }}'
          OSS_TOKEN: '${{ secrets.OSS_TOKEN }}'
          OSS_STAGING_PROFILE_ID: '${{ secrets.OSS_STAGING_PROFILE_ID }}'
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEYID }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGPASSWORD }}

      - name: Build and Release Branch
        if: ${{ github.ref_name != 'develop' && github.ref_name != 'main' }}
        run: |
          ./gradlew --no-daemon clean build -Psemver.develop.stage=alpha -PgitHubTokenProp=${{ github.token }} 
        env:
          TOKEN_GITHUB_ACTION: '${{ secrets.GITHUB_TOKEN }}'
          OSS_USER: '${{ secrets.OSS_USER }}'
          OSS_TOKEN: '${{ secrets.OSS_TOKEN }}'
          OSS_STAGING_PROFILE_ID: '${{ secrets.OSS_STAGING_PROFILE_ID }}'
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEYID }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGPASSWORD }}

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: build/test-results/**/*.xml

      - name: Publish Test Report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: build/reports/tests/test/*

      - name: Stop Gradle daemons
        run: ./gradlew --stop